### PR TITLE
docs: Added colab notebook for plotting artefact predictions

### PR DESCRIPTION
**Pull request by SiddhantBahuguna**
This PR adds the following feature to the existing repo:
It adds a colab notebook to plot the predictions of the artefact detection on the input images!

Any feedback is welcome!

### CODE REVIEW

**Review by fg-mindee — CHANGES_REQUESTED** [review]
Thanks for the PR! Looks good overall

A few comments to improve it further:
- FasterRCNN: perhaps you could add some references to the paper + add the illustration of how it works generally speaking (the ones you can find on internet, don't do one yourself). Make sure to credit the source and add it to improve the content
- text cells should be used more extensively: "imports" --> "Import all dependencies at once" / "helper functions" --> "everything you need to plot your model's predictions"
- a notebook isn't a script: everything you do inside "main", delete the function and simply paste the content in a new code cell :+1: Make sure to wrap `pred = model(img)` with the no_grad context like so:
```python
with torch.no_grad():
    pred = model(img)
```

You were correct, the plotted image is a bit small, could you modify this so that the plot is bigger please? :pray:

**Comment by SiddhantBahuguna** [comment]
> Thanks for the PR! Looks good overall
> 
> A few comments to improve it further:
> 
>     * FasterRCNN: perhaps you could add some references to the paper + add the illustration of how it works generally speaking (the ones you can find on internet, don't do one yourself). Make sure to credit the source and add it to improve the content
> 
>     * text cells should be used more extensively: "imports" --> "Import all dependencies at once" / "helper functions" --> "everything you need to plot your model's predictions"
> 
>     * a notebook isn't a script: everything you do inside "main", delete the function and simply paste the content in a new code cell +1 Make sure to wrap `pred = model(img)` with the no_grad context like so:
> 
> 
> ```python
> with torch.no_grad():
>     pred = model(img)
> ```
> 
> You were correct, the plotted image is a bit small, could you modify this so that the plot is bigger please? pray

Thank you so much for the review :)

**Review by fg-mindee — CHANGES_REQUESTED** [review]
Almost there!

- in the first text cell, use the markdown syntax to put the paper url as hyperlink on FasterRCNN
- novel region proposal network: hm hm, it's been 6 years now I think we can remove "novel" :sweat_smile: 
```
In this notebook, we will explore how to use a popular object detection architecture, [Faster-RCNN](https://arxiv.org/abs/1506.01497), to detect QR codes, bar codes, logos and ID pictures in documents.

Faster R-CNN is an end-to-end architecture, which leverages a dedicated module to generate region proposals (considerably more efficient than traditional algorithms like Selective Search). The features of those localization candidates are then extracted by an ROI Pooling layer to produce fixed-size feature maps from each candidate. The network can accurately and quickly predict the locations of different objects. Please refer to [Faster R-CNN Explained for Object Detection Tasks](https://blog.paperspace.com/faster-r-cnn-explained-object-detection/) for a quick introduction.

```

- can you change the title to "Object detection for artefacts in documents"?
- can you add three subsections ? (using `## Section title`) one called "Setup" right before installing requirements, one called "Inference utilities" before the imports, and a final one called "Visualizing your detections" after the cell with the plot_predictions definition
- About the path to the image: if that image can be shared publicly, I suggested, you provide the URL and we download it in the notebook so that users can run the whole notebook. If it's not, perhaps let's switch to one that can be shared

Thanks!

**Comment by SiddhantBahuguna** [comment]
> * Inference utilities
Thanks a lot again!

**Review by fg-mindee — CHANGES_REQUESTED** [review]
Two last things:
- mind moving the `!wget` to the import cell please? (to keep the last cell only for Python)
- the image clipping warning, is annoying but we can fix this:
```python
img = (255 * img.cpu().squeeze(0).permute(1, 2, 0).numpy()).round().astype(np.uint8)
```

**Review by fg-mindee — APPROVED** [review]
Thanks a lot!

**Pull request merged**
